version: 2.1

jobs:
  build-writerside-docs:
    docker:
      - image: cimg/base:current
    resource_class: nullops/builders
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Writerside Documentation"
          command: |
            docker run --rm \
              -v $(pwd)/docs:/opt/sources \
              -e INSTANCE=n \
              -e RUNNER=other \
              jetbrains/writerside-builder:2025.04.8412
      - run:
          name: "Extract build artifacts"
          command: |
            docker run --rm \
              -v $(pwd)/docs:/opt/sources \
              alpine:latest \
              sh -c "ls -la /opt/sources/artifacts || echo 'Artifacts directory not found'"
      - store_artifacts:
          path: docs/artifacts
          destination: documentation

workflows:
  build-documentation:
    jobs:
      - build-writerside-docs