echo "Building containers...";
docker compose down --remove-orphans;
docker compose build;
echo "Starting containers...";
docker compose up -d pgsql;
docker compose up -d nullops;
docker compose run --entrypoint "" -d nullops-testsuite tail -f /dev/null;
echo "Executing tests...";
docker compose exec nullops-testsuite /app/NullOps.Tests.E2ESuite;
docker compose down --remove-orphans *> $null;
