name: Build and deploy docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs-workflow.yml'

env:
  WRITERSIDE_VERSION: "2025.04.8412"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docs
        run: >
          docker run --rm -v ${{ github.workspace }}:/opt/sources
          -e SOURCE_DIR=/opt/sources/docs/
          -e MODULE_INSTANCE=Writerside/main
          -e OUTPUT_DIR=/opt/sources/output
          -e RUNNER=other
          -e PDF=PDF.xml
          jetbrains/writerside-builder:${{ env.WRITERSIDE_VERSION }}
