name: E2E tests
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/e2e-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run E2E tests
        working-directory: src
        run: dotnet run -c Release --project NullOps.Tests.E2ESuite/NullOps.Tests.E2ESuite.csproj
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-logs
          path: src/logs-*.log
          if-no-files-found: warn