name: Unit tests
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/unit-tests-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run E2E tests
        working-directory: src
        run: dotnet test --logger trx --results-directory "${{ github.workspace }}/TestResults"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: ${{ github.workspace }}/TestResults
        if: always()
