name: Unit tests
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/unit-tests-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run unit tests
        working-directory: src
        run: dotnet test --logger trx --results-directory "${{ github.workspace }}/TestResults"

      - name: Generate HTML report
        if: always()
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"${{ github.workspace }}/TestResults/*.trx" -targetdir:"${{ github.workspace }}/TestResults/" -reporttypes:Html_Dark,Markdown

      - name: Upload dotnet test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: ${{ github.workspace }}/TestResults

      - name: Deploy results to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy "${{ github.workspace }}/TestResults" --project-name=nullops-ut --branch=${{ github.ref_name }}-${{ github.sha }} --commit-hash=${{ github.sha }}
